### ISSUE TITLE
NotFound, message: "No such file or directory" 

### ISSUE THREAD

**Issue by rugk** [varjolintu/keepassxc-proxy-rust#6]
```sh
$ rustc -V
rustc 1.43.0
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/keepassxc-proxy`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:60:22
stack backtrace:
   0:     0x563039911865 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h837ee71a7893863c
   1:     0x563039928a4c - core::fmt::write::hc1676d0578e32d98
   2:     0x56303990fdc3 - std::io::Write::write_fmt::hd029acf5713f9fb9
   3:     0x563039913f00 - std::panicking::default_hook::{{closure}}::h84638efdfc6b1177
   4:     0x563039913c5c - std::panicking::default_hook::h9dc253b95e13cd46
   5:     0x563039914551 - std::panicking::rust_panic_with_hook::h65189b35fb88f950
   6:     0x56303991413b - rust_begin_unwind
   7:     0x563039927e61 - core::panicking::panic_fmt::h8a97d845ff5235ab
   8:     0x563039927c83 - core::option::expect_none_failed::h3941968acd66fe3d
   9:     0x56303990190b - core::result::Result<T,E>::unwrap::h9c7f694ca1582f8f
                               at /builddir/build/BUILD/rustc-1.43.0-src/src/libcore/result.rs:1003
  10:     0x5630398ffa4a - keepassxc_proxy::main::hdd67625c680dcb17
                               at src/main.rs:60
  11:     0x5630398fc8db - std::rt::lang_start::{{closure}}::hc85b52c5699bd8d6
                               at /builddir/build/BUILD/rustc-1.43.0-src/src/libstd/rt.rs:67
  12:     0x563039914013 - std::panicking::try::do_call::h5e9eee9a7b1ba1ad
  13:     0x563039916bf7 - __rust_maybe_catch_panic
  14:     0x563039914a6c - std::rt::lang_start_internal::hfddc200413ce6e5d
  15:     0x5630398fc8b7 - std::rt::lang_start::hf0683fcd57ae3355
                               at /builddir/build/BUILD/rustc-1.43.0-src/src/libstd/rt.rs:67
  16:     0x5630398ffafa - main
  17:     0x7f397a3b6042 - __libc_start_main
  18:     0x5630398fb22e - _start
  19:                0x0 - <unknown>
```

x86_64
Fedora 32

**Comment by varjolintu** [comment]
Check that the socket really exists in your TMPDIR or XDG_RUNGIME_DIR. I just encountered to this same problem yesterday when I tried a new branch where we changed the socket name from `kpxc_server` to `kpxc_browserserver`.

**Comment by RensOliemans** [comment]
I feel like this has the same cause as Issue #3 
I am on Debian Buster, and my socket seems to be
`/tmp/snap.keepasxc/tmp/keepassxc-rens.socket` (`rens` is my user)
So this proxy can't seem to find it, leading to the error above

**Comment by varjolintu** [comment]
The source is updated with the current socket name.
